
package com.rbc.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * hyd server -- http://10.211.70.180:9999/ws/demo?wsdl
 * local system -- http://10.211.70.130:9999/ws/demo?wsdl
 * ice server -- http://172.28.130.63:9999/ws/demo?wsdl
 * ice poc --- http://172.28.130.63:8380/WS_For_Jboss6/DocumentService?wsdl
 */
@WebServiceClient(name = "DocumentService", targetNamespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", wsdlLocation = "http://172.28.130.63:8380/WS_For_Jboss6/DocumentService?wsdl")
public class DocumentService
    extends Service
{

    private final static URL DOCUMENTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.rbc.ws.client.DocumentService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.rbc.ws.client.DocumentService.class.getResource(".");
            url = new URL(baseUrl, "http://172.28.130.63:8380/WS_For_Jboss6/DocumentService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://172.28.130.63:8380/WS_For_Jboss6/DocumentService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCUMENTSERVICE_WSDL_LOCATION = url;
    }

    public DocumentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentService() {
        super(DOCUMENTSERVICE_WSDL_LOCATION, new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "DocumentService"));
    }

    /**
     * 
     * @return
     *     returns DocumentServer
     */
    @WebEndpoint(name = "DocumentServerImplPort")
    public DocumentServer getDocumentServerImplPort() {
        return super.getPort(new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "DocumentServerImplPort"), DocumentServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentServer
     */
    @WebEndpoint(name = "DocumentServerImplPort")
    public DocumentServer getDocumentServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "DocumentServerImplPort"), DocumentServer.class, features);
    }

}
