
package com.rbc.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DocumentServer", targetNamespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage")
@XmlSeeAlso({
	ObjectFactoryF.class
})
public interface DocumentServer {


    /**
     * 
     * @param deleteAll
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delAll", targetNamespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", className = "com.rbc.ws.client.DelAll")
    @ResponseWrapper(localName = "delAllResponse", targetNamespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", className = "com.rbc.ws.client.DelAllResponse")
    public String delAll(
        @WebParam(name = "deleteAll", targetNamespace = "")
        boolean deleteAll);

    /**
     * 
     * @param serviceRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "serviceRequest", targetNamespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", className = "com.rbc.ws.client.ServiceRequest")
    @ResponseWrapper(localName = "serviceRequestResponse", targetNamespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", className = "com.rbc.ws.client.ServiceRequestResponse")
    public String serviceRequest(
        @WebParam(name = "ServiceRequest", targetNamespace = "")
        String serviceRequest);

}
