//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.02 at 02:23:18 PM IST 
//


package com.rbc.ws.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://RBCFG.WMS0.DocumentServices/ServiceMessage}objectMimeType"/>
 *         &lt;element ref="{http://RBCFG.WMS0.DocumentServices/ServiceMessage}objectContent"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentType", propOrder = {
    "objectMimeType",
    "objectContent"
})
public class ContentType {

    @XmlElement(required = true)
    protected ObjectMimeType objectMimeType;
    @XmlElement(required = true)
    protected byte[] objectContent;

    /**
     * Gets the value of the objectMimeType property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectMimeType }
     *     
     */
    public ObjectMimeType getObjectMimeType() {
        return objectMimeType;
    }

    /**
     * Sets the value of the objectMimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectMimeType }
     *     
     */
    public void setObjectMimeType(ObjectMimeType value) {
        this.objectMimeType = value;
    }

    /**
     * Gets the value of the objectContent property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getObjectContent() {
        return objectContent;
    }

    /**
     * Sets the value of the objectContent property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setObjectContent(byte[] value) {
        this.objectContent = ((byte[]) value);
    }

}
