//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.02 at 02:23:18 PM IST 
//


package com.rbc.ws.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocumentServiceRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentServiceRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://RBCFG.WMS0.DocumentServices/ServiceMessage}TransactionGUID"/>
 *         &lt;element ref="{http://RBCFG.WMS0.DocumentServices/ServiceMessage}TransactionType"/>
 *         &lt;element ref="{http://RBCFG.WMS0.DocumentServices/ServiceMessage}TransactionDescription"/>
 *         &lt;element ref="{http://RBCFG.WMS0.DocumentServices/ServiceMessage}TransactionDate"/>
 *         &lt;element ref="{http://RBCFG.WMS0.DocumentServices/ServiceMessage}TransactionTime"/>
 *         &lt;element ref="{http://RBCFG.WMS0.DocumentServices/ServiceMessage}IncludeDocumentImage" minOccurs="0"/>
 *         &lt;element ref="{http://RBCFG.WMS0.DocumentServices/ServiceMessage}MetaDataFields" minOccurs="0"/>
 *         &lt;element ref="{http://RBCFG.WMS0.DocumentServices/ServiceMessage}Packages" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentServiceRequestType", propOrder = {
    "transactionGUID",
    "transactionType",
    "transactionDescription",
    "transactionDate",
    "transactionTime",
    "includeDocumentImage",
    "metaDataFields",
    "packages"
})
public class DocumentServiceRequestType {

    @XmlElement(name = "TransactionGUID", required = true)
    protected String transactionGUID;
    @XmlElement(name = "TransactionType", required = true)
    protected String transactionType;
    @XmlElement(name = "TransactionDescription", required = true)
    protected String transactionDescription;
    @XmlElement(name = "TransactionDate", required = true)
    protected String transactionDate;
    @XmlElement(name = "TransactionTime", required = true)
    protected String transactionTime;
    @XmlElement(name = "IncludeDocumentImage")
    protected Boolean includeDocumentImage;
    @XmlElement(name = "MetaDataFields")
    protected MetaDataFields metaDataFields;
    @XmlElement(name = "Packages")
    protected PackagesType packages;

    /**
     * Gets the value of the transactionGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionGUID() {
        return transactionGUID;
    }

    /**
     * Sets the value of the transactionGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionGUID(String value) {
        this.transactionGUID = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionType(String value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the transactionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionDescription() {
        return transactionDescription;
    }

    /**
     * Sets the value of the transactionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionDescription(String value) {
        this.transactionDescription = value;
    }

    /**
     * Gets the value of the transactionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionDate() {
        return transactionDate;
    }

    /**
     * Sets the value of the transactionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionDate(String value) {
        this.transactionDate = value;
    }

    /**
     * Gets the value of the transactionTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionTime() {
        return transactionTime;
    }

    /**
     * Sets the value of the transactionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionTime(String value) {
        this.transactionTime = value;
    }

    /**
     * Gets the value of the includeDocumentImage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeDocumentImage() {
        return includeDocumentImage;
    }

    /**
     * Sets the value of the includeDocumentImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeDocumentImage(Boolean value) {
        this.includeDocumentImage = value;
    }

    /**
     * Gets the value of the metaDataFields property.
     * 
     * @return
     *     possible object is
     *     {@link MetaDataFields }
     *     
     */
    public MetaDataFields getMetaDataFields() {
        return metaDataFields;
    }

    /**
     * Sets the value of the metaDataFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaDataFields }
     *     
     */
    public void setMetaDataFields(MetaDataFields value) {
        this.metaDataFields = value;
    }

    /**
     * Gets the value of the packages property.
     * 
     * @return
     *     possible object is
     *     {@link PackagesType }
     *     
     */
    public PackagesType getPackages() {
        return packages;
    }

    /**
     * Sets the value of the packages property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackagesType }
     *     
     */
    public void setPackages(PackagesType value) {
        this.packages = value;
    }

}
