//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.02 at 02:23:18 PM IST 
//


package com.rbc.ws.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rbc.ws.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TransactionGUID_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "TransactionGUID");
    private final static QName _MetaDataFields_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "MetaDataFields");
    private final static QName _DocumentServiceRequest_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "DocumentServiceRequest");
    private final static QName _TransactionType_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "TransactionType");
    private final static QName _TransactionDate_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "TransactionDate");
    private final static QName _ObjectMimeType_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "objectMimeType");
    private final static QName _DocumentServices_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "DocumentServices");
    private final static QName _Content_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "Content");
    private final static QName _URL_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "URL");
    private final static QName _TransactionTime_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "TransactionTime");
    private final static QName _Recipient_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "Recipient");
    private final static QName _ResultCode_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "ResultCode");
    private final static QName _Package_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "Package");
    private final static QName _FaxNumber_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "FaxNumber");
    private final static QName _ResultDescription_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "ResultDescription");
    private final static QName _MetaDataField_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "MetaDataField");
    private final static QName _TransactionDescription_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "TransactionDescription");
    private final static QName _TransmittalMethod_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "TransmittalMethod");
    private final static QName _UserAuthRequest_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "UserAuthRequest");
    private final static QName _Recipients_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "Recipients");
    private final static QName _Document_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "Document");
    private final static QName _Packages_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "Packages");
    private final static QName _IncludeDocumentImage_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "IncludeDocumentImage");
    private final static QName _Documents_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "Documents");
    private final static QName _DocumentServiceResponse_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "DocumentServiceResponse");
    private final static QName _UserAuthResponse_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "UserAuthResponse");
    private final static QName _Application_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "Application");
    private final static QName _Name_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "Name");
    private final static QName _ObjectContent_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "objectContent");
    private final static QName _TransactionResult_QNAME = new QName("http://RBCFG.WMS0.DocumentServices/ServiceMessage", "TransactionResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rbc.ws.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserAuthResponseType }
     * 
     */
    public UserAuthResponseType createUserAuthResponseType() {
        return new UserAuthResponseType();
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link RecipientsType }
     * 
     */
    public RecipientsType createRecipientsType() {
        return new RecipientsType();
    }

    /**
     * Create an instance of {@link PackagesType }
     * 
     */
    public PackagesType createPackagesType() {
        return new PackagesType();
    }

    /**
     * Create an instance of {@link DocumentServicesType }
     * 
     */
    public DocumentServicesType createDocumentServicesType() {
        return new DocumentServicesType();
    }

    /**
     * Create an instance of {@link ApplicationType }
     * 
     */
    public ApplicationType createApplicationType() {
        return new ApplicationType();
    }

    /**
     * Create an instance of {@link MetaDataFields }
     * 
     */
    public MetaDataFields createMetaDataFields() {
        return new MetaDataFields();
    }

    /**
     * Create an instance of {@link UserAuthRequestType }
     * 
     */
    public UserAuthRequestType createUserAuthRequestType() {
        return new UserAuthRequestType();
    }

    /**
     * Create an instance of {@link DocumentServiceResponseType }
     * 
     */
    public DocumentServiceResponseType createDocumentServiceResponseType() {
        return new DocumentServiceResponseType();
    }

    /**
     * Create an instance of {@link DocumentServiceRequestType }
     * 
     */
    public DocumentServiceRequestType createDocumentServiceRequestType() {
        return new DocumentServiceRequestType();
    }

    /**
     * Create an instance of {@link ContentType }
     * 
     */
    public ContentType createContentType() {
        return new ContentType();
    }

    /**
     * Create an instance of {@link TransactionResultType }
     * 
     */
    public TransactionResultType createTransactionResultType() {
        return new TransactionResultType();
    }

    /**
     * Create an instance of {@link RecipientType }
     * 
     */
    public RecipientType createRecipientType() {
        return new RecipientType();
    }

    /**
     * Create an instance of {@link DocumentsType }
     * 
     */
    public DocumentsType createDocumentsType() {
        return new DocumentsType();
    }

    /**
     * Create an instance of {@link PackageType }
     * 
     */
    public PackageType createPackageType() {
        return new PackageType();
    }

    /**
     * Create an instance of {@link MetaDataFieldType }
     * 
     */
    public MetaDataFieldType createMetaDataFieldType() {
        return new MetaDataFieldType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "TransactionGUID")
    public JAXBElement<String> createTransactionGUID(String value) {
        return new JAXBElement<String>(_TransactionGUID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetaDataFields }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "MetaDataFields")
    public JAXBElement<MetaDataFields> createMetaDataFields(MetaDataFields value) {
        return new JAXBElement<MetaDataFields>(_MetaDataFields_QNAME, MetaDataFields.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentServiceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "DocumentServiceRequest")
    public JAXBElement<DocumentServiceRequestType> createDocumentServiceRequest(DocumentServiceRequestType value) {
        return new JAXBElement<DocumentServiceRequestType>(_DocumentServiceRequest_QNAME, DocumentServiceRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "TransactionType")
    public JAXBElement<String> createTransactionType(String value) {
        return new JAXBElement<String>(_TransactionType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "TransactionDate")
    public JAXBElement<String> createTransactionDate(String value) {
        return new JAXBElement<String>(_TransactionDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectMimeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "objectMimeType")
    public JAXBElement<ObjectMimeType> createObjectMimeType(ObjectMimeType value) {
        return new JAXBElement<ObjectMimeType>(_ObjectMimeType_QNAME, ObjectMimeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentServicesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "DocumentServices")
    public JAXBElement<DocumentServicesType> createDocumentServices(DocumentServicesType value) {
        return new JAXBElement<DocumentServicesType>(_DocumentServices_QNAME, DocumentServicesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "Content")
    public JAXBElement<ContentType> createContent(ContentType value) {
        return new JAXBElement<ContentType>(_Content_QNAME, ContentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "URL")
    public JAXBElement<String> createURL(String value) {
        return new JAXBElement<String>(_URL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "TransactionTime")
    public JAXBElement<String> createTransactionTime(String value) {
        return new JAXBElement<String>(_TransactionTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecipientType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "Recipient")
    public JAXBElement<RecipientType> createRecipient(RecipientType value) {
        return new JAXBElement<RecipientType>(_Recipient_QNAME, RecipientType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "ResultCode")
    public JAXBElement<Integer> createResultCode(Integer value) {
        return new JAXBElement<Integer>(_ResultCode_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PackageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "Package")
    public JAXBElement<PackageType> createPackage(PackageType value) {
        return new JAXBElement<PackageType>(_Package_QNAME, PackageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "FaxNumber")
    public JAXBElement<String> createFaxNumber(String value) {
        return new JAXBElement<String>(_FaxNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "ResultDescription")
    public JAXBElement<String> createResultDescription(String value) {
        return new JAXBElement<String>(_ResultDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetaDataFieldType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "MetaDataField")
    public JAXBElement<MetaDataFieldType> createMetaDataField(MetaDataFieldType value) {
        return new JAXBElement<MetaDataFieldType>(_MetaDataField_QNAME, MetaDataFieldType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "TransactionDescription")
    public JAXBElement<String> createTransactionDescription(String value) {
        return new JAXBElement<String>(_TransactionDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "TransmittalMethod")
    public JAXBElement<String> createTransmittalMethod(String value) {
        return new JAXBElement<String>(_TransmittalMethod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserAuthRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "UserAuthRequest")
    public JAXBElement<UserAuthRequestType> createUserAuthRequest(UserAuthRequestType value) {
        return new JAXBElement<UserAuthRequestType>(_UserAuthRequest_QNAME, UserAuthRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecipientsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "Recipients")
    public JAXBElement<RecipientsType> createRecipients(RecipientsType value) {
        return new JAXBElement<RecipientsType>(_Recipients_QNAME, RecipientsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "Document")
    public JAXBElement<DocumentType> createDocument(DocumentType value) {
        return new JAXBElement<DocumentType>(_Document_QNAME, DocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PackagesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "Packages")
    public JAXBElement<PackagesType> createPackages(PackagesType value) {
        return new JAXBElement<PackagesType>(_Packages_QNAME, PackagesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "IncludeDocumentImage")
    public JAXBElement<Boolean> createIncludeDocumentImage(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeDocumentImage_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "Documents")
    public JAXBElement<DocumentsType> createDocuments(DocumentsType value) {
        return new JAXBElement<DocumentsType>(_Documents_QNAME, DocumentsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "DocumentServiceResponse")
    public JAXBElement<DocumentServiceResponseType> createDocumentServiceResponse(DocumentServiceResponseType value) {
        return new JAXBElement<DocumentServiceResponseType>(_DocumentServiceResponse_QNAME, DocumentServiceResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserAuthResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "UserAuthResponse")
    public JAXBElement<UserAuthResponseType> createUserAuthResponse(UserAuthResponseType value) {
        return new JAXBElement<UserAuthResponseType>(_UserAuthResponse_QNAME, UserAuthResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "Application")
    public JAXBElement<ApplicationType> createApplication(ApplicationType value) {
        return new JAXBElement<ApplicationType>(_Application_QNAME, ApplicationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "objectContent")
    public JAXBElement<byte[]> createObjectContent(byte[] value) {
        return new JAXBElement<byte[]>(_ObjectContent_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", name = "TransactionResult")
    public JAXBElement<TransactionResultType> createTransactionResult(TransactionResultType value) {
        return new JAXBElement<TransactionResultType>(_TransactionResult_QNAME, TransactionResultType.class, null, value);
    }

}
