//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.02 at 02:23:18 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://RBCFG.WMS0.DocumentServices/ServiceMessage", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.rbc.ws.bean;
